# Generated by Django 2.2.2 on 2019-10-20 03:02

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vocabulary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meaning", models.CharField(max_length=255)),
                (
                    "level",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSpecific",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correct", models.PositiveIntegerField(default=0)),
                ("incorrect", models.PositiveIntegerField(default=0)),
                ("streak", models.PositiveIntegerField(default=0)),
                ("last_studied", models.DateTimeField(blank=True, null=True)),
                ("needs_review", models.BooleanField(default=True)),
                (
                    "unlock_date",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "next_review_date",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                    ),
                ),
                ("burned", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vocabulary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kw_webapp.Vocabulary",
                    ),
                ),
                ("hidden", models.BooleanField(default=False)),
                (
                    "wanikani_srs",
                    models.CharField(default="unknown", max_length=255),
                ),
                ("wanikani_srs_numeric", models.IntegerField(default=0)),
                ("wanikani_burned", models.BooleanField(default=False)),
                (
                    "notes",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("critical", models.BooleanField(default=False)),
                (
                    "wk_assignment_last_modified",
                    models.DateTimeField(null=True),
                ),
                ("meaning_note", models.CharField(max_length=2000, null=True)),
                ("reading_note", models.CharField(max_length=2000, null=True)),
                (
                    "wk_study_materials_last_modified",
                    models.DateTimeField(null=True),
                ),
            ],
            options={"unique_together": {("vocabulary", "user")}},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FrequentlyAskedQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=10000)),
                ("answer", models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name="PartOfSpeech",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character", models.CharField(max_length=255)),
                ("kana", models.CharField(max_length=255)),
                (
                    "level",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "vocabulary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="kw_webapp.Vocabulary",
                    ),
                ),
                ("common", models.NullBooleanField()),
                ("sentence_en", models.CharField(max_length=1000, null=True)),
                ("sentence_ja", models.CharField(max_length=1000, null=True)),
                ("tags", models.ManyToManyField(to="kw_webapp.Tag")),
                ("furigana", models.CharField(max_length=100, null=True)),
                ("pitch", models.CharField(max_length=100, null=True)),
                (
                    "parts_of_speech",
                    models.ManyToManyField(to="kw_webapp.PartOfSpeech"),
                ),
                (
                    "furigana_sentence_ja",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict, max_length=1000
                    ),
                ),
            ],
            options={"unique_together": {("vocabulary", "character", "kana")}},
        ),
        migrations.CreateModel(
            name="AnswerSynonym",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character", models.CharField(max_length=255, null=True)),
                ("kana", models.CharField(max_length=255)),
                (
                    "review",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_synonyms",
                        to="kw_webapp.UserSpecific",
                    ),
                ),
            ],
            options={"unique_together": {("character", "kana", "review")}},
        ),
        migrations.CreateModel(
            name="MeaningSynonym",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "review",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meaning_synonyms",
                        to="kw_webapp.UserSpecific",
                    ),
                ),
            ],
            options={"unique_together": {("text", "review")}},
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="parts_of_speech",
            field=models.ManyToManyField(to="kw_webapp.PartOfSpeech"),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="wk_last_modified",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="wk_subject_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="auxiliary_meanings_whitelist",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterModelManagers(name="userspecific", managers=[]),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=255, null=True)),
                ("gravatar", models.CharField(max_length=255)),
                (
                    "level",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "unlocked_levels",
                    models.ManyToManyField(to="kw_webapp.Level"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("about", models.CharField(default="", max_length=255)),
                ("api_valid", models.BooleanField(default=True)),
                ("join_date", models.DateField(auto_now_add=True, null=True)),
                ("posts_count", models.PositiveIntegerField(default=0)),
                (
                    "title",
                    models.CharField(
                        default="Turtles", max_length=255, null=True
                    ),
                ),
                ("topics_count", models.PositiveIntegerField(default=0)),
                (
                    "twitter",
                    models.CharField(default="N/A", max_length=255, null=True),
                ),
                (
                    "website",
                    models.CharField(default="N/A", max_length=255, null=True),
                ),
                ("follow_me", models.BooleanField(default=True)),
                (
                    "auto_advance_on_success",
                    models.BooleanField(default=False),
                ),
                (
                    "auto_expand_answer_on_failure",
                    models.BooleanField(default=False),
                ),
                ("on_vacation", models.BooleanField(default=False)),
                (
                    "vacation_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "last_wanikani_sync_date",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "auto_expand_answer_on_success",
                    models.BooleanField(default=True),
                ),
                (
                    "last_visit",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "minimum_wk_srs_level_to_review",
                    models.CharField(
                        choices=[
                            ("APPRENTICE", "Apprentice"),
                            ("GURU", "Guru"),
                            ("MASTER", "Master"),
                            ("ENLIGHTENED", "Enlightened"),
                            ("BURNED", "Burned"),
                        ],
                        default="APPRENTICE",
                        max_length=20,
                    ),
                ),
                (
                    "auto_advance_on_success_delay_milliseconds",
                    models.PositiveIntegerField(default=1000),
                ),
                (
                    "kanji_svg_draw_speed",
                    models.PositiveIntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("show_kanji_svg_grid", models.BooleanField(default=True)),
                (
                    "show_kanji_svg_stroke_order",
                    models.BooleanField(default=False),
                ),
                ("use_eijiro_pro_link", models.BooleanField(default=False)),
                (
                    "info_detail_level_on_failure",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(2)
                        ],
                    ),
                ),
                (
                    "info_detail_level_on_success",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(2)
                        ],
                    ),
                ),
                (
                    "maximum_wk_srs_level_to_review",
                    models.CharField(
                        choices=[
                            ("APPRENTICE", "Apprentice"),
                            ("GURU", "Guru"),
                            ("MASTER", "Master"),
                            ("ENLIGHTENED", "Enlightened"),
                            ("BURNED", "Burned"),
                        ],
                        default="BURNED",
                        max_length=20,
                    ),
                ),
                ("order_reviews_by_level", models.BooleanField(default=False)),
                ("api_key_v2", models.CharField(max_length=255, null=True)),
                ("burn_reviews", models.BooleanField(default=True)),
                ("has_lapsed_wanikani", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Date Published",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(max_length=1000)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="kw_webapp.Reading",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="userspecific",
            name="vocabulary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="kw_webapp.Vocabulary",
            ),
        ),
    ]
