# Generated by Django 2.2.4 on 2020-09-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0001_squashed_0044_merge_20191019_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='api_key',
        ),
    ]
