# Generated by Django 2.2.4 on 2020-09-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0002_remove_profile_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='manual_reading_whitelist',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
