# Generated by Django 2.2.20 on 2021-09-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0003_vocabulary_manual_reading_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_focus_on_advance',
            field=models.BooleanField(default=False),
        ),
    ]
