# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kw_webapp", "0015_auto_20160605_1254")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_visit",
            field=models.DateTimeField(auto_now_add=True, null=True),
        )
    ]
