# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-25 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kw_webapp", "0016_profile_last_visit")]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="reading",
            name="common",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="reading",
            name="jlpt",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="reading",
            name="sentence_en",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="reading",
            name="sentence_ja",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userspecific",
            name="notes",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="reading",
            name="tags",
            field=models.ManyToManyField(to="kw_webapp.Tag"),
        ),
    ]
