# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-24 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0018_auto_20161124_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partial',
            name='character',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
