# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-26 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kw_webapp", "0018_auto_20161211_1701")]

    operations = [
        migrations.AddField(
            model_name="level",
            name="partial",
            field=models.BooleanField(default=False),
        )
    ]
