# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-01 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kw_webapp", "0019_level_partial")]

    operations = [
        migrations.CreateModel(
            name="FrequentlyAskedQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=10000)),
                ("answer", models.CharField(max_length=10000)),
            ],
        )
    ]
