# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0022_auto_20170319_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='minimum_wk_srs_level_to_review',
            field=models.CharField(choices=[('APPRENTICE', 'apprentice'), ('GURU', 'guru'), ('MASTER', 'master'), ('ENLIGHTENED', 'enlightened'), ('BURNED', 'burned')], default='APPRENTICE', max_length=20),
        ),
    ]
