# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kw_webapp", "0023_auto_20170319_1335")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="minimum_wk_srs_level_to_review",
            field=models.CharField(
                choices=[
                    ("APPRENTICE", "Apprentice"),
                    ("GURU", "Guru"),
                    ("MASTER", "Master"),
                    ("ENLIGHTENED", "Enlightened"),
                    ("BURNED", "Burned"),
                ],
                default="APPRENTICE",
                max_length=20,
            ),
        )
    ]
