# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kw_webapp", "0024_auto_20170509_1348"),
        ("kw_webapp", "0024_auto_20170319_1549"),
    ]

    operations = []
