# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0025_merge_20170509_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspecific',
            name='last_studied',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
