# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kw_webapp", "0026_auto_20171117_1231"),
        ("kw_webapp", "0026_auto_20170815_0813"),
    ]

    operations = []
