# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-25 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kw_webapp', '0028_report'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userspecific',
            unique_together=set([('vocabulary', 'user')]),
        ),
    ]
