# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0033_auto_20180119_1214'),
    ]

    operations = [
        # WE have moved this stuff into migration 29, as it was actually needed there.
    ]
