# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0034_auto_20180219_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='kw_webapp.Reading'),
        ),
    ]
