# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 00:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kw_webapp', '0037_auto_20180321_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMeaningReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.PositiveIntegerField(default=0)),
                ('incorrect', models.PositiveIntegerField(default=0)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('last_studied', models.DateTimeField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=True)),
                ('next_review_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('burned', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('critical', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_meaning_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=255)),
                ('kana', models.CharField(max_length=255)),
                ('common', models.NullBooleanField()),
                ('sentence_en', models.CharField(max_length=1000, null=True)),
                ('sentence_ja', models.CharField(max_length=1000, null=True)),
                ('furigana', models.CharField(max_length=100, null=True)),
                ('pitch', models.CharField(max_length=100, null=True)),
                ('parts_of_speech', models.ManyToManyField(to='kw_webapp.PartOfSpeech')),
                ('tags', models.ManyToManyField(to='kw_webapp.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_vocabularies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customreading',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='kw_webapp.CustomVocabulary'),
        ),
        migrations.AddField(
            model_name='custommeaningreview',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kw_webapp.CustomVocabulary'),
        ),
        migrations.AlterUniqueTogether(
            name='customreading',
            unique_together=set([('character', 'kana')]),
        ),
        migrations.AlterUniqueTogether(
            name='custommeaningreview',
            unique_together=set([('vocabulary', 'user')]),
        ),
    ]
