# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 04:06
from __future__ import unicode_literals

from django.db import migrations, models
from kw_webapp import constants


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0037_auto_20180321_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='source',
            field=models.CharField(default=constants.Source.WANIKANI.name, max_length=255),
            preserve_default=False,
        ),
    ]
