# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0038_vocabulary_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='source',
            field=models.CharField(choices=[('WANIKANI', 'WaniKani'), ('JISHO', 'Jisho')], max_length=255),
        ),
    ]
