# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0039_auto_20180612_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='packs',
            field=models.ManyToManyField(to='kw_webapp.Pack'),
        ),
    ]
