# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-03 15:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("kw_webapp", "0037_auto_20180321_1551")]

    operations = [
        migrations.AddField(
            model_name="reading",
            name="furigana_sentence_ja",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default={}, max_length=1000
            ),
        )
    ]
