# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0040_auto_20180612_0056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSpecific',
            new_name='MeaningReview',
        ),
    ]
