# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-05 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0040_reading_furigana_sentence_ja'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='burn_reviews',
            field=models.BooleanField(default=True),
        ),
    ]
