# Generated by Django 2.2.2 on 2019-10-17 06:55

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0041_profile_burn_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reading',
            name='furigana_sentence_ja',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userspecific',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kw_webapp.Vocabulary'),
        ),
    ]
