# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-13 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kw_webapp", "0042_auto_20190112_0135")]

    operations = [
        migrations.AddField(
            model_name="userspecific",
            name="wk_last_modified",
            field=models.DateTimeField(null=True),
        )
    ]
