# Generated by Django 2.2.2 on 2019-10-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kw_webapp", "0042_auto_20191017_0255")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="has_lapsed_wanikani",
            field=models.BooleanField(default=False),
        )
    ]
