# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-18 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0043_userspecific_wk_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userspecific',
            old_name='wk_last_modified',
            new_name='wk_assignment_last_modified',
        ),
        migrations.AddField(
            model_name='userspecific',
            name='meaning_note',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='userspecific',
            name='reading_note',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='userspecific',
            name='wk_study_materials_last_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
