# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-28 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kw_webapp', '0044_auto_20190217_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='auxiliary_meanings_whitelist',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
