# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-28 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("kw_webapp", "0045_vocabulary_auxiliary_meanings_whitelist")
    ]

    operations = [
        migrations.AlterModelManagers(
            name="userspecific",
            managers=[("lessons", django.db.models.manager.Manager())],
        ),
        migrations.AlterField(
            model_name="profile",
            name="api_key",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
