# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-10 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("kw_webapp", "0046_auto_20190327_2119")]

    operations = [
        migrations.AlterModelManagers(name="userspecific", managers=[]),
        migrations.AlterUniqueTogether(
            name="reading",
            unique_together=set([("vocabulary", "character", "kana")]),
        ),
    ]
